<a href="https://colab.research.google.com/github/ajrianop/Data-Science-with-Python/blob/main/3_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exploratory Data Analysis (EDA)**

The following information are notes of the course from IBM skills builts.

The idea is to do the analysis the data, so we can summarize the general information, understand in a better way data sets, see the relation of each variable, extract the variables and study each one by its own.

Which are the characteristics related to the change or variation of variable `price`?

In order to solve this we need:
1. Descriptive statistics, which describes features of the dataset.
2. Grouping data.
3. ANOVA analysis of the variance, this is a statistical method which is used to compare the variaces between the mean and the different groups.
4. Correlation which allows us to see how the variables are related to the others.

## **Descriptive Statistics**

We have to describe that features of out datasets, and see about what talk our information. We can do that doing:


1.   Summarizing statistical data with `df.describe()`.
2.   Summarizing information of the categorical data using `df['column'].value_counts()` and see the amount of data what we have by category.
3.   Box.plots, which are a visualization tool, which represent the information given by quartiles, we can see that:

*   Lower extreme -> 1.5 times the interquartile range below the 25th percentile
*   Lower quartile -> 25th percentile
*   Median -> 50th percentile
*   Upper quartile -> 75th percentile
*   Upper extrema -> 1.5 times the interquartile range above the 75th percentile
*   Outliers -> Individual dots that occurs outside the upper and lower extremes

With this graphs we can see the skewness of the data
4. Scatter plot: describes the relation between two variables, is represented as points.

*   predictor axis x
*   target axis y

## **Grouping data**

We can group the data according to the variables posed, we can divided the information by means the values in the categorical data an so on classify or generated some groups. We can group a single value or several variables.
We can lead on this using the method `df.groupby([columns])`. Over this information we can compute specific information, as the mean, mode, std between other methods.

### **pivot()**

The `df.pivot(index= 'first-variable', columns='second-variable')` consist in displayed one of values of a variable as columns, and the other values of the variable as rows, so, we can compute in a different order the specific information that we want as computing the mean, the median, std...

We can also visualized the previous method as a plot using heatmaps. So we can plot
`plt.pcolor(df_pivot, cmap='color-palette')`

## **ANOVA - ANalysis Of VAriation**

As we said before ANOVA is a statistical method that stands for "Analysis of variations".<br>

This method can be used to find correlation between different groups of variables.<br>

We obtain from this method two values:


1.   F-test score: the ratio of variation between the groups's mean over the variation the ratio of variation between the groups's mean over the variation. https://en.wikipedia.org/wiki/F-test
2.   p-value: compute the statistical significance

To take in mind we have if the F-test score is less than 1 and the p-value is larger than 0.05 the data is not significantly different, but if the F-test score is higher than one and the p-value is larger than 0.05 then both variables are significantly different.

According to that we can said that there exists a strong correlation between variables if the ANOVA test give us a larger F-value score and a small p-value (in some cases we take values less than 0.05 and if we want more precision les than 0.01, the last one use with medical information)

## **Correlation**

Correlation in statistics it normally refers to the degree to which a pair of variables are linearly related (interdependant). So we have to see when one variable increase the other could mantain the same behaviour or also could be the opposite.
To take into account this mean not is the same as causation.
We have positive correlation, negative correlation and weak correlation, this could be seen in the scatter plot descriptions.

**Pearson correlation**
We can measure the strenght of the correlation, so the pearson correlation give us two values:


1.   Correlation coefficient:

*   Large positive relation values close to +1.
*   Large negative relation values close to-1.
*   No relationship values close to 0.


2.   P-value:
*   Strong certainty in the result with P-value < 0.001
*   Moderate certainty in the result with P-value < 0.05
*   Weak certainty in the result with P-value < 0.1
*   No certainty in the result with P-value > 0.1

# **EDA dataset clean-auto**

## **Import libraries**

We are going to use a dataset taken from IBM Skills Builts. So

In [6]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [3]:
df = pd.read_csv("/content/gdrive/MyDrive/Programming Topics/Data Science/data/automobileEDA.csv")
df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

## **Taking a look of data**

We want to see what type of data has each of the column in the dataframe.

In [9]:
#Looking the types of the dataframe
df.dtypes

symboling              int64
normalized-losses      int64
make                  object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
city-L/100km         float64
horsepower-binned     object
diesel                 int64
gas                    int64
dtype: object

We can note that the type of information with we are working are int, float and object types. Some of the type object are categorical functions.

It is important to study how the data is related with each other, so the best idea to see how this occurs is seeing the correlation table, which describes if the variables are linearly correlated

In [10]:
df.corr()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
symboling,1.000000,0.466264,-0.535987,-0.365404,-0.242423,-0.550160,-0.233118,-0.110581,-0.140019,-0.008245,-0.182196,0.075819,0.279740,-0.035527,0.036233,-0.082391,0.066171,-0.196735,0.196735
normalized-losses,0.466264,1.000000,-0.056661,0.019424,0.086802,-0.373737,0.099404,0.112360,-0.029862,0.055563,-0.114713,0.217299,0.239543,-0.225016,-0.181877,0.133999,0.238567,-0.101546,0.101546
wheel-base,-0.535987,-0.056661,1.000000,0.876024,0.814507,0.590742,0.782097,0.572027,0.493244,0.158502,0.250313,0.371147,-0.360305,-0.470606,-0.543304,0.584642,0.476153,0.307237,-0.307237
length,-0.365404,0.019424,0.876024,1.000000,0.857170,0.492063,0.880665,0.685025,0.608971,0.124139,0.159733,0.579821,-0.285970,-0.665192,-0.698142,0.690628,0.657373,0.211187,-0.211187
width,-0.242423,0.086802,0.814507,0.857170,1.000000,0.306002,0.866201,0.729436,0.544885,0.188829,0.189867,0.615077,-0.245800,-0.633531,-0.680635,0.751265,0.673363,0.244356,-0.244356
height,-0.550160,-0.373737,0.590742,0.492063,0.306002,1.000000,0.307581,0.074694,0.180449,-0.062704,0.259737,-0.087027,-0.309974,-0.049800,-0.104812,0.135486,0.003811,0.281578,-0.281578
curb-weight,-0.233118,0.099404,0.782097,0.880665,0.866201,0.307581,1.000000,0.849072,0.644060,0.167562,0.156433,0.757976,-0.279361,-0.749543,-0.794889,0.834415,0.785353,0.221046,-0.221046
engine-size,-0.110581,0.112360,0.572027,0.685025,0.729436,0.074694,0.849072,1.000000,0.572609,0.209523,0.028889,0.822676,-0.256733,-0.650546,-0.679571,0.872335,0.745059,0.070779,-0.070779
bore,-0.140019,-0.029862,0.493244,0.608971,0.544885,0.180449,0.644060,0.572609,1.000000,-0.055390,0.001263,0.566936,-0.267392,-0.582027,-0.591309,0.543155,0.554610,0.054458,-0.054458
stroke,-0.008245,0.055563,0.158502,0.124139,0.188829,-0.062704,0.167562,0.209523,-0.055390,1.000000,0.187923,0.098462,-0.065713,-0.034696,-0.035201,0.082310,0.037300,0.241303,-0.241303
compression-ratio,-0.182196,-0.114713,0.250313,0.159733,0.189867,0.259737,0.156433,0.028889,0.001263,0.187923,1.000000,-0.214514,-0.435780,0.331425,0.268465,0.071107,-0.299372,0.985231,-0.985231
horsepower,0.075819,0.217299,0.371147,0.579821,0.615077,-0.087027,0.757976,0.822676,0.566936,0.098462,-0.214514,1.000000,0.107885,-0.822214,-0.804575,0.809575,0.889488,-0.169053,0.169053
peak-rpm,0.279740,0.239543,-0.360305,-0.285970,-0.245800,-0.309974,-0.279361,-0.256733,-0.267392,-0.065713,-0.435780,0.107885,1.000000,-0.115413,-0.058598,-0.101616,0.115830,-0.475812,0.475812
city-mpg,-0.035527,-0.225016,-0.470606,-0.665192,-0.633531,-0.049800,-0.749543,-0.650546,-0.582027,-0.034696,0.331425,-0.822214,-0.115413,1.000000,0.972044,-0.686571,-0.949713,0.265676,-0.265676
highway-mpg,0.036233,-0.181877,-0.543304,-0.698142,-0.680635,-0.104812,-0.794889,-0.679571,-0.591309,-0.035201,0.268465,-0.804575,-0.058598,0.972044,1.000000,-0.704692,-0.930028,0.198690,-0.198690
price,-0.082391,0.133999,0.584642,0.690628,0.751265,0.135486,0.834415,0.872335,0.543155,0.082310,0.071107,0.809575,-0.101616,-0.686571,-0.704692,1.000000,0.789898,0.110326,-0.110326
city-L/100km,0.066171,0.238567,0.476153,0.657373,0.673363,0.003811,0.785353,0.745059,0.554610,0.037300,-0.299372,0.889488,0.115830,-0.949713,-0.930028,0.789898,1.000000,-0.241282,0.241282
diesel,-0.196735,-0.101546,0.307237,0.211187,0.244356,0.281578,0.221046,0.070779,0.054458,0.241303,0.985231,-0.169053,-0.475812,0.265676,0.198690,0.110326,-0.241282,1.000000,-1.000000
gas,0.196735,0.101546,-0.307237,-0.211187,-0.244356,-0.281578,-0.221046,-0.070779,-0.054458,-0.241303,-0.985231,0.169053,0.475812,-0.265676,-0.198690,-0.110326,0.241282,-1.000000,1.000000

We are going to study the previous dataset, let us see some statistical information

In [4]:
#summarize statistical information about our variables
df.describe()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,197.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.840796,122.00000,98.797015,0.837102,0.915126,53.766667,2555.666667,126.875622,3.330692,3.256904,10.164279,103.405534,5117.665368,25.179104,30.686567,13207.129353,9.944145,0.099502,0.900498
std,1.254802,31.99625,6.066366,0.059213,0.029187,2.447822,517.296727,41.546834,0.268072,0.319256,4.004965,37.365700,478.113805,6.423220,6.815150,7947.066342,2.534599,0.300083,0.300083
min,-2.000000,65.00000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,0.000000,101.00000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000,7.833333,0.000000,1.000000
50%,1.000000,122.00000,97.000000,0.832292,0.909722,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5125.369458,24.000000,30.000000,10295.000000,9.791667,0.000000,1.000000
75%,2.000000,137.00000,102.400000,0.881788,0.925000,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000,12.368421,0.000000,1.000000
max,3.000000,256.00000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          201 non-null    int64
 1   normalized-losses  201 non-null    int64
 2   make               201 non-null    object
 3   aspiration         201 non-null    object
 4   num-of-doors       201 non-null    object
 5   body-style         201 non-null    object
 6   drive-wheels       201 non-null    object
 7   engine-location    201 non-null    object
 8   wheel-base         201 non-null    float64
 9   length             201 non-null    float64
 10  width              201 non-null    float64
 11  height             201 non-null    float64
 12  curb-weight        201 non-null    int64
 13  engine-type        201 non-null    object
 14  num-of-cylinders   201 non-null    object
 15  engine-size        201 non-null    int64
 16  fuel-system        201 non-null    object
 17  bore               201 non-null    float64
 18  stroke             197 non-null    float64
 19  compression-ratio  201 non-null    float64
 20  horsepower         201 non-null    float64
 21  peak-rpm           201 non-null    float64
 22  city-mpg           201 non-null    int64
 23  highway-mpg        201 non-null    int64
 24  price              201 non-null    float64
 25  city-L/100km       201 non-null    float64
 26  horsepower-binned  200 non-null    object
 27  diesel             201 non-null    int64
 28  gas                201 non-null    int64
dtypes: float64(11), int64(8), object(10)
memory usage: 45.7+ KB

In [ ]:
#summarize the categorical data using value count